repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: local
    hooks:
      - id: busted-tests
        name: Run busted tests
        entry: busted --coverage tests/ --pattern='test_.*.lua'
        language: system
        types: [lua]
      - id: busted-coverage
        name: Run busted coverage
        entry: |
          luacov --pattern='modules/*.lua' \
          && grep '^modules/.*[0-9]%$' luacov.report.out \
          | awk '{hits+=$2; missed+=$3} END {printf "Total Hits: %d\nTotal Missed: %d\nCoverage: %.2f%%\n", hits, missed, hits/(hits+missed)*100}'
        language: system
        types: [lua]
      - id: luacheck-lint
        name: Run luacheck lint
        entry: luacheck modules
        language: system
        types: [lua]
      - id: markdownlint
        name: Lint Markdown
        entry: npx markdownlint-cli '**/*.md'
        language: system
        types: [markdown]
